sudo: false
language: go
go:
- 1.11.x
go_import_path: github.com/grpc-ecosystem/grpc-health-probe
git:
  depth: 1
install: true
notifications:
  email: false
before_install:
- go get -u github.com/mitchellh/gox
script:
- env -u GOPATH gox -output='out/grpc_health_probe-{{.OS}}-{{.Arch}}' -rebuild -os=linux
  -arch="386 amd64 ppc64le arm arm64" -tags netgo -ldflags=-w
deploy:
  on:
    repo: p1c2u/grpc-health-probe
    tags: true
  provider: releases
  file_glob: true
  file: out/grpc_health_probe-*
  skip_cleanup: true
  options:
    prerelease: true
  api_key:
    secure: jNWeZ0fAKGHH7gLt34BggQ/VwAaX+0ePerpFsj5u0Ndqzb+4uFaQ0ZuJ187AgbOpyJQRUwk1EcKoL5ltQgP9KttuDd13w9t2qatb0BmeG3f/oFWwwh1uvqCqVYZDXcyqK/2haLA50gvndgtSgUwq8Esn27jWQHZgSd/LvsvNdeHZ5VJaWNcp7nq3DX3jdhNLwGt5YOiSjUzKXX7rU21yPbN6ezn87gpm58JUpY6zhVjYcKhFz9xui/cx6QejQH2n6BFQ+WKL0fS/p5M43f7fqb6ni6Ed/mBDuMqfN8qVVvUONlrS1ByMKyy0mr8KDOTcjtgqK5K0liRBRyiF61k94ofa1sGyZpSjlF+FOaofbsv1JKtQK1C1lcAwKLf4TEuhygBj5/3pgm+0PG92JKe6H5cWVQjMCbaCrV2yLXfvyr2drzRyZTlH6GGRJ2utYYQolbTBG2NT/D0esHkAS6tuWJBkIeOzpsySKWq9CFKotQv9n4Rt8qSLsSfJQxwFRga8daDdEV2W29f2XsHjp2YSRGCEPBBfwrqCg1lojQapZ6XDHWFIcmeHGNioVK2eDpb9+S5lt1IRVMH01RrqI6PzzQf2GgjFRQn+4/2wc2DJV1wbRNVhvNRrfNjnQZBU8bc5W/UvWNbrp3rUXhpF7aXWTVf93U0sX2dXl8ug4OdF5OQ=
